/** @type {import('tailwindcss').Config} */
// Design system ported from the Stitch mockup. Colors are driven by CSS custom
// properties (see src/index.css :root / .dark) so the whole palette swaps for
// dark mode without per-element `dark:` variants. Each token is written as
// `oklch(var(--c-x) / <alpha-value>)` so Tailwind opacity modifiers still work.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface": "oklch(var(--c-surface) / <alpha-value>)",
        "warning-bg": "oklch(var(--c-warning-bg) / <alpha-value>)",
        "on-surface-variant": "oklch(var(--c-on-surface-variant) / <alpha-value>)",
        "on-error-container": "oklch(var(--c-on-error-container) / <alpha-value>)",
        "on-tertiary-container": "oklch(var(--c-on-tertiary-container) / <alpha-value>)",
        "on-error": "oklch(var(--c-on-error) / <alpha-value>)",
        "primary": "oklch(var(--c-primary) / <alpha-value>)",
        "on-secondary-container": "oklch(var(--c-on-secondary-container) / <alpha-value>)",
        "success-fg": "oklch(var(--c-success-fg) / <alpha-value>)",
        "tertiary-fixed-dim": "oklch(var(--c-tertiary-fixed-dim) / <alpha-value>)",
        "outline": "oklch(var(--c-outline) / <alpha-value>)",
        "surface-tint": "oklch(var(--c-surface-tint) / <alpha-value>)",
        "ink-4": "oklch(var(--c-ink-4) / <alpha-value>)",
        "primary-fixed-dim": "oklch(var(--c-primary-fixed-dim) / <alpha-value>)",
        "primary-container": "oklch(var(--c-primary-container) / <alpha-value>)",
        "tertiary-container": "oklch(var(--c-tertiary-container) / <alpha-value>)",
        "surface-container-high": "oklch(var(--c-surface-container-high) / <alpha-value>)",
        "hairline": "oklch(var(--c-hairline) / <alpha-value>)",
        "secondary-fixed": "oklch(var(--c-secondary-fixed) / <alpha-value>)",
        "on-secondary": "oklch(var(--c-on-secondary) / <alpha-value>)",
        "on-secondary-fixed-variant": "oklch(var(--c-on-secondary-fixed-variant) / <alpha-value>)",
        "error-container": "oklch(var(--c-error-container) / <alpha-value>)",
        "secondary-fixed-dim": "oklch(var(--c-secondary-fixed-dim) / <alpha-value>)",
        "surface-dim": "oklch(var(--c-surface-dim) / <alpha-value>)",
        "bg-tint": "oklch(var(--c-bg-tint) / <alpha-value>)",
        "accent-bg": "oklch(var(--c-accent-bg) / <alpha-value>)",
        "accent": "oklch(var(--c-accent) / <alpha-value>)",
        "ink-2": "oklch(var(--c-ink-2) / <alpha-value>)",
        "secondary": "oklch(var(--c-secondary) / <alpha-value>)",
        "border-2": "oklch(var(--c-border-2) / <alpha-value>)",
        "surface-container-low": "oklch(var(--c-surface-container-low) / <alpha-value>)",
        "tertiary-fixed": "oklch(var(--c-tertiary-fixed) / <alpha-value>)",
        "inverse-primary": "oklch(var(--c-inverse-primary) / <alpha-value>)",
        "error": "oklch(var(--c-error) / <alpha-value>)",
        "on-secondary-fixed": "oklch(var(--c-on-secondary-fixed) / <alpha-value>)",
        "bg": "oklch(var(--c-bg) / <alpha-value>)",
        "on-tertiary": "oklch(var(--c-on-tertiary) / <alpha-value>)",
        "on-tertiary-fixed-variant": "oklch(var(--c-on-tertiary-fixed-variant) / <alpha-value>)",
        "background": "oklch(var(--c-background) / <alpha-value>)",
        "border": "oklch(var(--c-border) / <alpha-value>)",
        "outline-variant": "oklch(var(--c-outline-variant) / <alpha-value>)",
        "warning-fg": "oklch(var(--c-warning-fg) / <alpha-value>)",
        "secondary-container": "oklch(var(--c-secondary-container) / <alpha-value>)",
        "surface-variant": "oklch(var(--c-surface-variant) / <alpha-value>)",
        "ink-3": "oklch(var(--c-ink-3) / <alpha-value>)",
        "on-primary": "oklch(var(--c-on-primary) / <alpha-value>)",
        "on-primary-fixed": "oklch(var(--c-on-primary-fixed) / <alpha-value>)",
        "on-primary-fixed-variant": "oklch(var(--c-on-primary-fixed-variant) / <alpha-value>)",
        "surface-container-lowest": "oklch(var(--c-surface-container-lowest) / <alpha-value>)",
        "on-background": "oklch(var(--c-on-background) / <alpha-value>)",
        "tertiary": "oklch(var(--c-tertiary) / <alpha-value>)",
        "on-primary-container": "oklch(var(--c-on-primary-container) / <alpha-value>)",
        "success-bg": "oklch(var(--c-success-bg) / <alpha-value>)",
        "inverse-surface": "oklch(var(--c-inverse-surface) / <alpha-value>)",
        "on-surface": "oklch(var(--c-on-surface) / <alpha-value>)",
        "surface-2": "oklch(var(--c-surface-2) / <alpha-value>)",
        "ink": "oklch(var(--c-ink) / <alpha-value>)",
        "primary-fixed": "oklch(var(--c-primary-fixed) / <alpha-value>)",
        "on-tertiary-fixed": "oklch(var(--c-on-tertiary-fixed) / <alpha-value>)",
        "surface-container": "oklch(var(--c-surface-container) / <alpha-value>)",
        "surface-container-highest": "oklch(var(--c-surface-container-highest) / <alpha-value>)",
        "inverse-on-surface": "oklch(var(--c-inverse-on-surface) / <alpha-value>)",
        "surface-bright": "oklch(var(--c-surface-bright) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "padding-component": "12px 20px",
        "gap-md": "18px",
        "gutter-default": "16px",
        "gap-regular": "12px",
        "content-max-width": "820px",
        "gap-tight": "4px",
        "sidebar-width": "280px",
      },
      fontFamily: {
        "body-primary": ["Geist", "sans-serif"],
        "body-secondary": ["Geist", "sans-serif"],
        "mono-telemetry": ["Geist Mono", "monospace"],
        "mono-label-xs": ["Geist Mono", "monospace"],
        "ui-label": ["Geist", "sans-serif"],
        "markdown-h3": ["Geist", "sans-serif"],
        "display-cover": ["Geist", "sans-serif"],
        "hero-heading": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-primary": ["14.5px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-secondary": ["13.5px", { lineHeight: "1.5", fontWeight: "400" }],
        "mono-telemetry": ["11px", { lineHeight: "1.4", fontWeight: "400" }],
        "mono-label-xs": ["10px", { lineHeight: "1.0", fontWeight: "500" }],
        "ui-label": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "markdown-h3": ["15px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-cover": ["64px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "600" }],
        "hero-heading": ["28px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "caret-blink": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.25s ease-out both",
        "fade-in-up": "fade-in-up 0.35s cubic-bezier(0.16, 1, 0.3, 1) both",
        "slide-in-right": "slide-in-right 0.3s cubic-bezier(0.16, 1, 0.3, 1) both",
        "scale-in": "scale-in 0.2s cubic-bezier(0.16, 1, 0.3, 1) both",
        "caret-blink": "caret-blink 1s steps(1) infinite",
      },
    },
  },
  plugins: [],
}
