/** @type {import('tailwindcss').Config} */
// Design system ported verbatim from the Stitch mockup (<script id="tailwind-config">).
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "oklch(1 0 0)",
        "warning-bg": "oklch(0.96 0.04 90)",
        "on-surface-variant": "#444655",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#fffbff",
        "on-error": "#ffffff",
        primary: "#264dd9",
        "on-secondary-container": "#fffbff",
        "success-fg": "oklch(0.38 0.08 150)",
        "tertiary-fixed-dim": "#ffb68e",
        outline: "#747686",
        "surface-tint": "#294fdb",
        "ink-4": "oklch(0.68 0.009 250)",
        "primary-fixed-dim": "#b8c3ff",
        "primary-container": "#4568f3",
        "tertiary-container": "#be5600",
        "surface-container-high": "#e8e8ee",
        hairline: "oklch(0.94 0.005 250)",
        "secondary-fixed": "#e1e0ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c0c1ff",
        "surface-dim": "#d9d9df",
        "bg-tint": "oklch(0.975 0.004 250)",
        "accent-bg": "oklch(0.96 0.025 265)",
        accent: "oklch(0.5 0.13 265)",
        "ink-2": "oklch(0.36 0.012 250)",
        secondary: "#4648d4",
        "border-2": "oklch(0.86 0.006 250)",
        "surface-container-low": "#f3f3f9",
        "tertiary-fixed": "#ffdbc9",
        "inverse-primary": "#b8c3ff",
        error: "#ba1a1a",
        "on-secondary-fixed": "#07006c",
        bg: "oklch(0.985 0.003 250)",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#763300",
        background: "#f9f9ff",
        border: "oklch(0.92 0.005 250)",
        "outline-variant": "#c4c5d7",
        "warning-fg": "oklch(0.4 0.07 75)",
        "secondary-container": "#6063ee",
        "surface-variant": "#e2e2e8",
        "ink-3": "oklch(0.52 0.011 250)",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001355",
        "on-primary-fixed-variant": "#0035bd",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1a1c20",
        tertiary: "#974300",
        "on-primary-container": "#fffbff",
        "success-bg": "oklch(0.95 0.045 150)",
        "inverse-surface": "#2f3035",
        "on-surface": "#1a1c20",
        "surface-2": "oklch(0.965 0.004 250)",
        ink: "oklch(0.22 0.012 250)",
        "primary-fixed": "#dde1ff",
        "on-tertiary-fixed": "#331200",
        "surface-container": "#ededf3",
        "surface-container-highest": "#e2e2e8",
        "inverse-on-surface": "#f0f0f6",
        "surface-bright": "#f9f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "padding-component": "12px 20px",
        "gap-md": "18px",
        "gutter-default": "16px",
        "gap-regular": "12px",
        "content-max-width": "820px",
        "gap-tight": "4px",
        "sidebar-width": "280px",
      },
      fontFamily: {
        "body-primary": ["Geist", "sans-serif"],
        "body-secondary": ["Geist", "sans-serif"],
        "mono-telemetry": ["Geist Mono", "monospace"],
        "mono-label-xs": ["Geist Mono", "monospace"],
        "ui-label": ["Geist", "sans-serif"],
        "markdown-h3": ["Geist", "sans-serif"],
        "display-cover": ["Geist", "sans-serif"],
        "hero-heading": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-primary": ["14.5px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-secondary": ["13.5px", { lineHeight: "1.5", fontWeight: "400" }],
        "mono-telemetry": ["11px", { lineHeight: "1.4", fontWeight: "400" }],
        "mono-label-xs": ["10px", { lineHeight: "1.0", fontWeight: "500" }],
        "ui-label": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "markdown-h3": ["15px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-cover": ["64px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "600" }],
        "hero-heading": ["28px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
